// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621155618_Add_Watches_Table")]
    partial class Add_Watches_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("HasPublicProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("has_public_profile");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Domain.Users.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "Domain.Users.User.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Watches.Entities.WatchAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BraceletType")
                        .HasColumnType("integer")
                        .HasColumnName("bracelet_type");

                    b.Property<int>("CaseMaterial")
                        .HasColumnType("integer")
                        .HasColumnName("case_material");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("Movement")
                        .HasColumnType("integer")
                        .HasColumnName("movement");

                    b.Property<int>("Occasion")
                        .HasColumnType("integer")
                        .HasColumnName("occasion");

                    b.Property<int>("Style")
                        .HasColumnType("integer")
                        .HasColumnName("style");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Brand", "Domain.Watches.Entities.WatchAggregate.Brand#Brand", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("brand");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DialColor", "Domain.Watches.Entities.WatchAggregate.DialColor#DialColor", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("dial_color");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dimensions", "Domain.Watches.Entities.WatchAggregate.Dimensions#WatchDimensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("CaseThicknessMm")
                                .HasColumnType("numeric")
                                .HasColumnName("case_thickness_mm");

                            b1.Property<decimal>("LugToLugMm")
                                .HasColumnType("numeric")
                                .HasColumnName("lug_to_lug_mm");

                            b1.Property<decimal>("LugWidthMm")
                                .HasColumnType("numeric")
                                .HasColumnName("lug_width_mm");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CaseDiameter", "Domain.Watches.Entities.WatchAggregate.Dimensions#WatchDimensions.CaseDiameter#CaseDiameter", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Mm")
                                        .HasColumnType("numeric")
                                        .HasColumnName("case_diameter_mm");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Model", "Domain.Watches.Entities.WatchAggregate.Model#Model", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("model");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Domain.Watches.Entities.WatchAggregate.Price#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Eur")
                                .HasColumnType("numeric")
                                .HasColumnName("price_eur");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ReferenceNumber", "Domain.Watches.Entities.WatchAggregate.ReferenceNumber#ReferenceNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("reference_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_watches");

                    b.ToTable("watches", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
